### ISSUE TITLE
Bizarre KeyError: 'imdbId'

### ISSUE THREAD

**Issue by Yankees4life** [excludarr/excludarr#12]
**Describe the bug**
I tried using this to hunt down some radarr titles that are in my streaming service and this bizarre keyerror occured. "KeyError: 'imdbId'"

**To Reproduce**
`excludarr radarr exclude -a delete -d -e`

**Expected behavior**
A list of movies that are on my streaming services and a prompt to confirm I'm deleting them

**Versions**
1. OS Version: win10
2. Excludarr version: 1.0.8
3. Python version:  3.11

**Debug logging**
https://gist.github.com/Yankees4life/9c6b7ab0cc3127416e97b966ed739f05

**Comment by barsa2000** [comment]
Yea, this should also get fixed by the pull request I made, It's an error related to not making sure that the `imdbId` is populated on radarr
