### ISSUE TITLE
JustWatch API calls no longer work

### ISSUE THREAD

**Issue by scott-es** [excludarr/excludarr#2]
_recreating issue for tracking_

Has been throwing the error excludarr.modules.justwatch.exceptions.JustWatchNotFound since 2023/10/12

see original issue for historical details https://github.com/haijeploeg/excludarr/issues/92

**Comment by scott-es** [comment]
From a technical perspective, using this project https://github.com/Electronic-Mango/simple-justwatch-python-api seems to be the best route, however as noted in prior discussion on the [original issue](https://github.com/haijeploeg/excludarr/issues/92#issuecomment-1994145234) that project is [GPLv3](https://fossa.com/blog/open-source-software-licenses-101-gpl-v3/) licensed.

GPLv3 allows for using the code similar to MIT except for the fact that the consuming projects also have to be GPLv3 (strict copyleft).

current (MIT) license allows us to change the license of this fork to GPLv3, so we could do that and just use this working python client.

@TheArturthur thoughts?  I don't see any issue but maybe I'm missing something

**Comment by scott-es** [comment]
https://github.com/excludarr/excludarr/pull/4

**Comment by scott-es** [comment]
@TheArturthur as I am trying to go through the code and make updates, I found that for movies it seems straightforward (have started to make those changes for `radarr` related functionality), however for shows (sonarr related functionality) it does not appear the information about seasons and episodes is exposed currently through the justwatch client. 

[See this issue](https://github.com/Electronic-Mango/simple-justwatch-python-api/issues/7)

I propose then that the next change is to update excludarr to use the justwatch client for the radarr-related flows only and temporarily disable functionality for the sonarr-related ones (any command using sonarr verb will get an error message thats its temporarily disabled -- which I think is fine since its currently broken anyway).

hopefully someone (if not one of us) will update the justwatch client to include the additional data at which point later we can updated excludarr to utilize it.

Thoughts?

**Comment by TheArturthur** [comment]
Fine by me, it would also be nice to update the README or show that error message for all current commands, as they don't work either.
I will jump back with this as soon as I have the time for it.

**Comment by babsonnexus** [comment]
> [See this issue](https://github.com/Electronic-Mango/simple-justwatch-python-api/issues/7)

> hopefully someone (if not one of us) will update the justwatch client to include the additional data at which point later we can updated excludarr to utilize it.

I'm unfamiliar with the project here, but I was able to build out more GraphQL-JustWatch features than simple-justwatch-python-api and do a whole lot more with it. It was a great starting point and an important inspiration / learning area, however my project's needs went far beyond what it could offer. Check it out if you have a chance:

https://github.com/babsonnexus/stream-link-manager-for-channels

**Comment by barsa2000** [comment]
> > [See this issue](https://github.com/Electronic-Mango/simple-justwatch-python-api/issues/7)
> 
> 
> 
> > hopefully someone (if not one of us) will update the justwatch client to include the additional data at which point later we can updated excludarr to utilize it.
> 
> 
> 
> I'm unfamiliar with the project here, but I was able to build out more GraphQL-JustWatch features than simple-justwatch-python-api and do a whole lot more with it. It was a great starting point and an important inspiration / learning area, however my project's needs went far beyond what it could offer. Check it out if you have a chance:
> 
> 
> 
> https://github.com/babsonnexus/stream-link-manager-for-channels

Good for you, I simply wrote manually the 2/3 queries with the datapoints we needed

Check out [our JustWatch module](https://github.com/excludarr/excludarr/tree/main/excludarr/modules/justwatch)
