### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by luis4ndre** [excludarr/excludarr#5]
Sorry for my ignorance, I'm trying to run Excludarr on Windows 11.
I installed it via PIP but I don't know where to put the configuration file.
Could you help me please?

Thanks

**Comment by TheArturthur** [comment]
If you check the README, under [Configuration](https://github.com/excludarr/excludarr?tab=readme-ov-file#configuration) it says the following:
> To configure the application make sure that one of the following files exists:
```
/etc/excludarr/excludarr.yml
~/.config/excludarr/excludarr.yml
~/.excludarr/config/excludarr.yml
~/.excludarr.yml
./.excludarr.yml
```
> The application will read those configuration files in that order. So ./.excludarr.yml will overwrite /etc/excludarr/excludarr.yml. > For a full list of options and their description see [excludarr-example.yml](https://github.com/excludarr/excludarr/blob/main/.examples/excludarr-example.yml) in this repository.

In the case of Windows, `~/` refers to `C:\Users\<username>`, but Python should interpret `~/` correctly.

I would recommend you use any of the `~/` options, as they would prevail no matter the directory you're running the command from, and work both in Linux/Mac and Windows.

However, please note this is a fork of the original repo, which is the one the PIP package uses (noted for future releases). Currently, neither this fork nor the original repo works, as said in [#92](https://github.com/haijeploeg/excludarr/issues/92) and [#2 ](https://github.com/excludarr/excludarr/issues/2).
